services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - 54327:5432
    environment:
      - POSTGRES_PASSWORD=wongrapee
      - POSTGRES_USER=wongrapee
      - POSTGRES_DB=wongrapee
    volumes:
      - ./data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    container_name: 69-s1-admin
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data-admin:/var/lib/pgadmin
