services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - 54327:5432
    environment:
      - POSTGRES_PASSWORD=wongrapee
      - POSTGRES_USER=wongrapee
      - POSTGRES_DB=wongrapee
    volumes:
      - ./data:/var/lib/postgresql/data
 admin:
    image: dpage/pgadmin4
    container_name: 69-s1-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=wongrapee-s@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=wongrapee
    ports:
      - "8081:80"
    depends_on:
      - db
